repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-merge-conflict
    - id: check-yaml
    - id: check-added-large-files
      args: ['--maxkb=5120']
    - id: trailing-whitespace