MACHINE:
  SEED: 1224460545
EXPORT:
  NUM_POINTS: 2000000
  FUSION_MAX_DEPTH: 5.0
  SEQ_RANSAC:
    ITER: 1500
    OFFSET_THRESHOLD: 0.08  # meter
    NORMAL_THRESHOLD: 20  # degree
EVAL:
  NUM_POINTS: 200000